export const ERROR_MESSAGES = {
  MONGO_URI_NOT_DEFINED: "MONGO_URI is not defined in environment variables.",
  MONGO_CONNECTION_FAILED: "MongoDB connection error:",
  JWT_NOT_DEFINED: "JWT_SECRET is not defined in environment variables.",
  EMAIL_IN_USE: "Email already in use.",
  INVALID_CREDENTIALS: "Invalid credentials.",
  INVALID_PARAMETERS: "Invalid email parameter",
  SERVER_ERROR: "An internal server error occurred.",
  TOKEN_MISSING_OR_MALFORMED: "Authorization token missing or malformed.",
  TOKEN_INVALID_OR_EXPIRED: "Invalid or expired token.",
  NOT_FOUND: "User Not found",
  REFRESH_NOT_DEFINED: "REFRESH_TOKEN is not defined in environment variables.",
  ACCESS_DENIED: "Access denied: Admins only.",
  INVALID_INPUT: "Invalid year parameter.",
  UPDATE_USER_ERROR: "User could not be updated.",
  DELETE_USER_ERROR: "User could not be deleted.",
  CREATE_ADMIN_ERROR: "Admin could not be created.",
  USER_NOT_CREATED: "Error creating user",
  FETCH_ADMIN_ERROR: "Admin not found.",
  USER_NOT_FOUND: "User not Found.",
  USERS_NOT_FOUND: "Users not Found.",
  UPDATE_ADMIN_ERROR: "Admin could not be updated.",
  ACCESS_DENIED_NOT_SUPER_ADMIN: "Access denied: Super Admins only.",
  BLOG_ALREADY_EXIST: "Blog with this title already exists",
  BLOG_CATEGORY_ALREADY_EXIST: "Blog Category with this title already exists",
  INTERNAL_ERROR: "Internal server error",
  UNAUTHORIZED: "User is not Authorized",
  ORG_NOT_FOUND: "Organization not found",
  ABOUT_KEKA_NOT_FOUND: "Entry not found",
  ABOUT_KEKA_NOT_DELETED: "Entry could not be deleted",
  ORG_ALREADY_EXISTS: "Organization with this email already exists",
  CREDENTIALS_NOT_PROVIDED: "Please enter the credentials.",
  DATA_NOT_INSERTED: "Data not inserted.",
  MISSING_FIELDS: "Missing required fields.",
  DATA_ALREADY_EXISTS: "Data already exists in the database.",
  DATA_NOT_FOUND: "Data not found in the database.",
  DATA_NOT_UPDATED: "Data could not be updated.",
  CREATE_JOB_FAILED: "Failed to create the job.",
  FETCH_JOBS_FAILED: "Failed to fetch the jobs.",
  JOB_NOT_FOUND: "Job not found.",
  UPDATE_JOB_FAILED: "Failed to update the job.",
  DELETE_JOB_FAILED: "Failed to delete the job.",
  NO_JOBS_FOUND: "No jobs found in the database.",
  POST_NOT_CREATED: "Error creating in post",
  POST_NOTFOUND_UNAUTHORIZED: "Post not found or unauthorized",
  POST_DELETE_ERROR: "Error in deleting the post",
  POST_SEARCHING_ERROR: "Error in seraching",
  POST_GETTING_ERROR: "Error in geting all post ",
  POST_UPDATING_ERROR: "Error in deleting the post",
  EMAIL_NOT_FOUND: "Email not found",
  LANDING_CARD_NOT_FOUND: "Landing card not found",
  USER_ALREADY_EXISTS: "User already exists.",
  TEAM_MEMBER_NOT_FOUND: "Team member not found.",
  WRONG_PASSWORD: "Wrong password. Please try again.",
  BOTH_PASSWORDS_REQUIRED: "Old and new passwords are required.",
  REQUEST_FAILED: "Request could not be completed.",
  CREATING_JOB_DETAILS_ERROR: "Error creating job details",
  JOB_DETAILS_ALREADY_EXISTS: "Job details already exist for this user.",
  JOB_DETAILS_NOT_FOUND: "Details Not Found",
  DEPARTMENT_NOT_FOUND: "Department not found",
  DEPARTMENT_NOT_CREATED: "Failed to create department",
  UPDATE_FAILED: "Failed to update department",
  DELETE_FAILED: "Failed to delete department",
  DEPT_FETCH: "Error fetching department ID:",
  LOGO_UPLOAD_FAILED: "Failed to upload logo",
  LOGO_NOT_FOUND: "Organization or logo not found",
  LOGO_NOT_DELETE: "Failed to delete logo",
  LOGO_NOT_UPLOADED: "No file uploaded",
  ASSIGN_ASSETS_ERROR: "Error assigning asset",
  RETURN_ASSETS_ERROR: "Error returning asset",
  ASSET_NOT_APPROVED: "Asset request is not approved.",
  ASSET_UPDATE_ERROR: "Error updating asset.",
  RECEIVE_ASSET_ERROR: "Error receiving asset.",
  ERROR_CREATING_CATEGORY: "Error creating category",
  ERROR_UPDATING_CATEGORY: "Error updating category.",
  DATA_NOT_FETCHED: "Data could not be fetched.",
  DATA_NOT_DELETED: "Data could not be deleted.",
  GLOSSARY_NOT_CREATED: "Glossary could not be created.",
  GLOSSARY_NOT_FETCHED: "Glossary could not be fetched.",
  ANN_NOT_FOUND: "No announcements found.",
  ANN_NOT_UPDATED: "Announcement could not be updated.",
  ANN_NOT_CREATED: "Announcement could not be created.",
  FETCH_ANN_ERROR: "Announcement could not be fetched.",
  CREATE_RELATION_ERROR: "Error creating relation",
  RELATION_NOT_FOUND: "Relation not found",
  CATEGORY_NOT_FOUND: "Category not found",
  ERROR_DELETING_CATEGORY: "error deleting category",
  ERROR_CREATING_RATING: "error creating rating",
  FAILED_TO_GET_RATING: "Failed to compute average rating",
  CONTACT_NOT_CREATED: "Contact could not be created.",
  CREATE_EMPLOYEE_FAILED: "Employee profile couldn't be created",
  LEAVE_APPLY_FAILED: "Failed to apply leave",
  DOCUMENT_NOT_FOUND: "Document not found",
  DOCUMENT_NOT_UPLOADED: "Error in uploading document",
  DOCUMENT_NOT_DELETED: "Error in deleting document",
  DOCUMENT_NOT_EDITED: "Error in editing document",
  DOCUMENT_NOT_FETCHED: "Error in fetching document",
  S3_UPLOAD_ERROR: "Failed to upload file to S3",
  S3_DELETE_ERROR: "Failed to delete file from S3",
  CONTACT_NOT_DELETED: "Contact could not be deleted.",
  CONTACT_NOT_FOUND: "Contact could not be found.",
  UNAUTHORIZED_ACTION: "You are not authorized to perform this action.",
  DELETE_ANN_ERROR: "Announcement could not be deleted.",
  GLOSSARY_MISSING_FIELD: "Glossary term or definition is missing.",
  NO_VALID_FIELD: "Please provide valid fields to update.",
  SEARCH_USER_IN_DEPT: "Both name and departmentName are required.",
  HOLIDAY_ALREADY_EXISTS: "Holiday with this name already exists.",
  HOLIDAY_NOT_FOUND: "Holiday not found.",
  HOLIDAY_NOT_CREATED: "Holiday could not be created.",
  HOLIDAY_NOT_UPDATED: "Holiday could not be updated.",
  HOLIDAY_NOT_DELETED: "Holiday could not be deleted.",
  ALREADY_CHECKED_IN: "Already checked in without checkout.",
  NO_CHECK_IN_FOUND: "No check-in found for today.",
  ALREADY_CHECKED_OUT: "Already checked out.",
  NO_ATTENDANCE_RECORD: "No attendance record found for the specified date.",
  ALL_FIELDS_REQUIRED: " All fields are required.",
  POLL_NOT_CREATED: "Error in creating poll",
  POLL_NOT_FOUND: "Poll not found.",
  POLLS_NOT_FOUND: "Polls not found.",
  POLL_NOT_UPDATED: "Poll not updated.",
  POLL_NOT_DELETED: "Poll not deleted.",
  POLL_OPTION_NOT_DELETED: "Poll option not deleted.",
  POLL_DATA_INVALID: "Invalid poll data",
  POLL_NOT_VOTED: "Poll not voted.",
  POLL_NOT_REMOVED: "Poll option not removed.",
  FAILED_FETCH_REFRESH: "Failed to refresh access token",
  INVALID_FIELDS: "Entered fields are invalid.",
  PROJECT_EXISTS:"Project with this name already exists",
  NO_PROJECTS_FOUND: "No projects found.",
  ATTENDANCE_CHECK_IN_FAILED: "Attendance check-in failed.",
  ATTENDANCE_CHECK_OUT_FAILED: "Attendance check-out failed.",
  ATTENDANCE_GET_TOTAL_DURATION_FAILED: "Failed to get total duration.",
  ATTENDANCE_HISTORY_FETCH_FAILED: "Failed to fetch attendance history.",
  ATTENDANCE_HISTORY_NOT_FOUND: "Attendance history not found.",
};
