export const SUCCESS_MESSAGES = {
  MONGO_CONNECTION_SUCCESS: (host: string) => `MongoDB Connected: ${host}`,
  USER_REGISTERED: "User registered successfully.",
  LOGIN_SUCCESSFUL: "Login successful.",
  SERVER_RUNNING: (port: string | number) =>
    `Server is running on port ${port}.`,
  REGISTERED_SUCCESS:
    "Organization registered, logged in successfully, and confirmation email sent",
  ORG_REGISTER_LOGIN:
    "Organization registered, logged in successfully, and confirmation email sent",
  USER_DELETED: "User deleted successfully.",
  USER_UPDATED: "User updated successfully.",
  USER_FOUND: "User found.",
  USERS_FOUND: "Users found.",
  USER_NOT_FOUND: "User not found.",
  USER_PROFILE_UPDATED: "User profile updated successfully.",
  DESCRIPTION_UPDATED: "User description updated successfully.",
  DESCRIPTION_ADDED: "Description added successfully.",
  Holiday_Deleted: "Holiday Deleted Successfully",
  HOLIDAY_CREATED: "Holiday Created Successfully",
  DATA_UPDATED: "New data has been added to Database.",
  DATA_FOUND: "Requested data found.",
  DATA_DELETED: "Data deleted successfully.",
  DATA_CREATED: "Data created successfully.",
  BLOG_CREATED: "Blog created successfully.",
  BLOG_UPDATED: "Blog updated successfully.",
  BLOG_DELETED: "Blog deleted successfully.",
  BLOG_RETRIEVED: "Blog retrieved successfully.",
  BLOG_ALREADY_EXIST: "Blog with this title already exists",
  BLOG_CATEGORY_CREATED: "Blog category created successfully.",
  BLOG_CATEGORY_UPDATED: "Blog category updated successfully.",
  BLOG_CATEGORY_DELETED: "Blog category deleted successfully.",
  BLOG_CATEGORY_RETRIEVED: "Blog category retrieved successfully.",
  TEAM_MEMBER_UPDATED: "Team member updated successfully.",
  TEAM_MEMBER_DELETED: "Team member deleted successfully.",
  TEAM_MEMBER_RETRIEVED: "Team member retrieved successfully.",
  TEAM_MEMBER_ADDED: "Team member added successfully.",
  TEAM_MEMBER_EXISTS: "Team member with this name already exists",
  USER_CREATED: "User created successfully",
  ORG_DELETED: "Organization deleted successfully",
  ORG_UPDATE: "Organization updated successfully",
  ORG_CREATED: "Organization created successfully",
  JOB_DELETED: "Job deleted successfully.",
  JOB_UPDATED: "Job updated successfully.",
  JOB_FETCHED: "Job fetched successfully.",
  POST_DELETE: "Post deleted successfully",
  POST_RETRIVED: "Post retrived successfully",
  RATING_CREATED: "Thank you for your rating.",
  TOTAL_RATING: "Total rating retrieved successfully.",
  LANDING_CARD_CREATED: "Landing card created successfully",
  LANDING_CARD_FETCHED: "Landing card fetched successfully",
  LANDING_CARD_UPDATED: "Landing card updated successfully",
  CAREER_PAGE_DATA: "Career page data retrieved",
  POST_CREATED: "Post created successfully",
  ABOUT_KEKA_RETRIEVED: "About Keka details retrieved successfully.",
  ABOUT_KEKA_UPDATED: "About Keka details updated successfully.",
  ABOUT_KEKA_POSTED: "About Keka details posted successfully.",
  CONTACT_SUBMITTED: "contact sunbmitted successfully",
  CONTACT_FETCHED: "Contact details fetched succesfully.",
  PASSWORD_CHANGED: "password Change successfully",
  PASSWORD_RESET: "password reset successfully",
  CONTACT_DELETED: "Contact deleted succesfully.",
  JOB_DETAILS_ADDED: "Job details added successfully.",
  JOB_DETAILS_UPDATED: "Job details updated successfully.",
  JOB_DETAILS_DELETED: "Job details deleted successfully.",
  JOb_DETAILS_RETRIEVED: "Job details retrieved successfully.",
  USER_FOUND_LOGIN: "User Found kindly Login",
  DEPARTMENT_CREATED: "Department created successfully",
  DEPARTMENT_UPDATED: "Department updated successfully",
  DEPARTMENT_DELETED: "Department deleted successfully",
  DEPARTMENT_DATA_FOUND: "Data found successfully",
  LOGO_UPLOADED: "Logo uploaded successfully",
  LOGO_DELETED: "Logo deleted successfully",
  ASSETS_REQUSTED_SEND: "Asset request sent successfully.",
  ASSETS_STATUS_UPDATED: "Assets status updated successfully.",
  ASSETS_UPDATED : "Assets updated successfully.",
  ASSETS_APPROVED_REQUEST: "Asset request has been approved.",
  ASSETS_REJECTED_REQUEST: "Asset request has been rejected.",
  ASSETS_DELETED : "Assets deleted successfully.",
  ASSETS_REQUESTS: "Assets requests retrieved successfully.",
  ASSIGNED_ASSETS: "Assigned assets retrieved successfully.",
  ASSETS_FETCHED: "Assets fetched successfully.",
  ASSETS_LIST: "Assets list retrieved successfully.",
  EMAIL_SENT: "Password reset email sent successfully.",
  ANN_CREATED: "Announcement created succesfully.",
  ANN_UPDATED: "Announcement updated succesfully.",
  ANN_FTECHED: "Announcement fetched succesfully",
  ANN_DELETED: "Announcement deleted succesfully.",
  REALTION_ADDED: "Relation Added successfully",
  PASSWORD_EMAIL_SEND: "Password reset email send successfully.",
  GET_ALL_EMPLOYEE: "All Employees fetched successfully",
  JOB_CREATED: "Job created successfully",
  ORGS_FETCHED: "Organisations fetched succesfully.",
  ORG_FETCHED: "Organisation fetched succesfully.",
  EMPLOYEE_PROFILE_CREATED: "Employee profile created",
  LEAVE_APPLIED: "Leave applied successfully.",
  LEAVE_UPDATED: "Leave updated successfully.",
  LEAVE_FETCHED: "Leave fetched successfully.",
  GLOSSARY_DELETED: "Glossary deleted successfully.",
  GLOSSARY_UPDATED: "Glossary updated successfully.",
  GLOSSARY_CREATED: "Glossary created successfully.",
  GLOSSARY_FTETCHED: "Glossary fetched successfully.",
  HOLIDAY_UPDATED: " Holiday updated successfully",
  HOLIDAY_DELETED: " Holiday deleted successfully",
  HOLIDAY_RETRIVED: " Holiday retrived successfully",
  DOCUMENT_UPLOADED: "Document uploaded successfully",
  DOCUMENT_DELETED: "Document deleted successfully",
  DOCUMENT_UPDATED: "Document updated successfully",
  DOCUMENT_FETCHED: "Document fetched successfully",
  CHECKED_IN: "Checked in successfully",
  CHECKED_OUT: "Checked out successfully",
  TOTAL_DURATION_CALCULATED: "Total duration calculated successfully",
  ATTENDANCE_HISTORY_FETCHED: "Attendance history fetched successfully",
  BADGE_CREATED: "Badge created successfully",
  BADGE_FETHED: "Badge fetched successfully",
  PRAISE_POSTED: "Praise posted successfully",
  PRAISE_FETCHED: "Praise fetched successfully",
  PRAISE_UPDATED: "Praise updated successfully",
  PRAISE_DELETED: "Praise deleted successfully",
  POLL_CREATED: "Poll created successfully",
  POLL_UPDATED: "Poll updated successfully",
  POLL_DELETED: "Poll deleted successfully",
  POLL_FETCHED: "Poll fetched successfully",
  POLL_VOTE_SUBMITTED: "Vote submitted successfully",
  POLLS_FETCHED: "Polls fetched successfully",
  POLL_VOTE_UPDATED: "Vote updated successfully",
  ABOUT_KEKA_DELETED: "Details deleted successfully",
  POLL_OPTION_REMOVED: "Option removed successfully",
  ACCESS_TOKEN_REFRESHED: "Access token refreshed successfully",
  PROJECT_ADDED: "Project added successfully",
  PROJECT_FETCHED: "Project fetched successfully",
};
